spring:
  datasource:
    url: jdbc:mysql://student-debate-management.chjfpzpmnkau.ap-northeast-1.rds.amazonaws.com:3306/student_debate_management_db
    username: root
    password: arkadyuti

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  output:
    ansi:
      enabled: ALWAYS

server:
  servlet:
    context-path: /spring-debate-management-demo

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss})  %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

    level:
      root: ERROR
      org:
        hibernate:
          type: TRACE

#security:
#  headers:
#    cache: false